ifndef::snippets[]
:snippets: ../../../build/generated-snippets
endif::[]
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:
:operation-http-request-title: Example Request
:operation-http-response-title: Example Response
[[resources]]
= Resources

[[resources-members]]
== Member

[[resources-members-create]]
=== 회원 가입

operation::members/create[snippets='http-request,http-response,request-fields']

[[resources-oauth-token-bearer]]
=== 로그인

operation::oauth/token/bearer[snippets='http-request,request-fields,http-response,response-fields']

[[resources-me-bearer-update]]
=== 회원 정보 수정

operation::me/bearer/update[snippets='http-request,request-headers,request-body,request-fields']

[[resources-me-bearer-delete]]
=== 회원 탈퇴

operation::me/bearer/delete[snippets='http-request,request-headers']

[[resources-favorites]]
== Favorite

[[resources-favorites-create]]
=== 즐겨찾기 생성

operation::favorites/create[snippets='http-request,request-headers,request-fields,http-response,response-headers']

[[resources-favorites-show]]
=== 즐겨찾기 조회

operation::favorites/show[snippets='http-request,request-headers,http-response,response-fields']

[[resources-favorites-delete]]
=== 즐겨찾기 삭제

operation::favorites/delete[snippets='http-request,request-headers,request-fields']