ifndef::snippets[]
:snippets: ../../../build/generated-snippets
endif::[]
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:
:operation-http-request-title: Example Request
:operation-http-response-title: Example Response

[[resources]]
= Resources

[[resources-admin-members]]
== Member(Admin)

[[resources-admin-members-create]]
=== 회원 가입

operation::admin/members/create[snippets='http-request,request-fields,http-response,response-headers']

[[resources-admin-members-get]]
=== 회원정보 검색

operation::admin/members/get[snippets='http-request,request-parameters,http-response,response-fields']

[[resources-admin-members-update]]
=== 회원정보 수정

operation::admin/members/update[snippets='http-request,path-parameters,request-headers,request-fields,http-response']

[[resources-admin-members-delete]]
=== 회원정보 삭제

operation::admin/members/delete[snippets='http-request,path-parameters,http-response']

[[resources-user]]
== Member(User)

[[resources-user-create]]
=== 회원 가입

operation::user/create[snippets='http-request,request-fields,http-response']

[[resources-user-login]]
=== 로그인

operation::user/login[snippets='http-request,request-fields,http-response,response-fields']

[[resources-user-get]]
=== 개인정보 조회

operation::user/get[snippets='http-request,request-headers,http-response,response-fields']

[[resources-user-update]]
=== 개인정보 수정

operation::user/update[snippets='http-request,request-headers,request-fields,http-response']

[[resources-user-delete]]
=== 회원 탈퇴

operation::user/delete[snippets='http-request,request-headers,http-response']

[[resources-user-favorite-create]]
=== 즐겨찾기 추가

operation::user/favorite/create[snippets='http-request,request-headers,request-fields,http-response']

[[resources-user-favorite-getAll]]
=== 즐겨찾기 조회

operation::user/favorite/getAll[snippets='http-request,request-headers,http-response,response-fields']

[[resources-user-favorite-delete]]
=== 즐겨찾기 삭제

operation::user/favorite/delete[snippets='http-request,request-headers,request-fields,http-response']