ifndef::snippets[]
:snippets: ../../../build/generated-snippets
endif::[]
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:
:operation-http-request-title: Example Request
:operation-http-response-title: Example Response

[[resources]]
= Resources

[[resources-members]]
== Member

[[resources-members-create]]
=== 회원 가입

operation::members/create[snippets='http-request,http-response,request-fields']

[[resources-members-update]]
=== 회원 수정

operation::members/update[snippets='http-request,http-response,request-fields']

[[resources-members-delete]]
=== 회원 삭제

operation::members/delete[snippets='http-request,http-response']

[[resources-favorites]]
== Favorites

[[resources-favorites-add]]
=== 즐겨찾기 추가

operation::favorites/add[snippets='http-request,http-response']

[[resources-favorite-get]]
=== 즐겨찾기 불러오기

operation::favorites/get[snippets='http-request,http-response,path-parameters']

[[resources-favorites-read]]
=== 즐겨찾기 목록 불러오기

operation::favorites/read[snippets='http-request,http-response']

[[resources-favorites-delete]]
=== 즐겨찾기 삭제 (Source & Target)

operation::favorites/delete[snippets='http-request,http-response']

[[resources-favorites-deleteById]]
=== 즐겨찾기 삭제 (id)

operation::favorites/deleteById[snippets='http-request,http-response']

[[resources-loginMember]]
== LoginMember

[[resources-loginMember-login]]
=== 로그인

operation::loginMember/login[snippets='http-request,http-response,request-fields']

[[resources-loginMember-get]]
=== 로그인 멤버 불러오기

operation::loginMember/get[snippets='http-request,http-response']

[[resources-loginMember-update]]
=== 로그인 멤버 수정

operation::loginMember/update[snippets='http-request,http-response,request-fields']

[[resources-loginMember-delete]]
=== 로그인 멤버 삭제

operation::loginMember/delete[snippets='http-request,http-response']