ifndef::snippets[]
:snippets: ../../../build/generated-snippets
endif::[]
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:
:operation-http-request-title: Example Request
:operation-http-response-title: Example Response

[[resources]]
= Resources

[[resources-members]]
== 회원 관리

[[resources-members-create]]
=== 회원 추가
operation::members/create[snippets='http-request,http-response']

[[resources-members-get]]
=== 회원 조회
operation::members/get[snippets='http-request,http-response']

[[resources-members-update]]
=== 회원 수정
operation::members/update[snippets='http-request,http-response']

[[resources-members-delete]]
=== 회원 삭제
operation::members/delete[snippets='http-request,http-response']

[[resources-me]]
== 본인의 정보 관리

[[resources-me-login]]
=== 로그인
operation::me/login[snippets='http-request,http-response']

[[resources-me-get]]
=== 본인의 정보 가져오기
operation::me/get[snippets='http-request,http-response']

[[resources-me-update]]
=== 본인의 정보 수정
operation::me/update[snippets='http-request,http-response']

[[resources-me-delete]]
=== 본인의 정보 삭제
operation::me/delete[snippets='http-request,http-response']

[[resources-me-favorites]]
== 본인의 즐겨찾기 관리

[[resources-me-favorites-get]]
=== 본인의 즐겨찾기 가져오기
operation::me/favorites/get[snippets='http-request,http-response']

[[resources-me-favorites-create]]
=== 본인의 즐겨찾기 추가
operation::me/favorites/create[snippets='http-request,http-response']

[[resources-me-favorites-delete]]
=== 본인의 즐겨찾기 삭제
operation::me/favorites/delete[snippets='http-request,http-response']

