ifndef::snippets[]
:snippets: ../../../build/generated-snippets
endif::[]
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
:operation-http-request-title: Example Request
:operation-http-response-title: Example Response

[[resources]]
= Resources

[[resources-members]]
== Member

[[resources-members-create]]
=== 회원 가입

[[resources-members-create-success]]
===== 성공
operation::members/create[snippets='http-request,http-response,request-fields']


[[resources-members-create-fail]]
==== 실패

[[resources-members-create-fail-duplicated-email]]
===== 이메일 중복
operation::members/duplicate-create[snippets='http-request,http-response,request-fields']


[[resources-members-create-fail-not-match-password]]
===== 패스워드 불일치
operation::members/not-match-password-create[snippets='http-request,http-response,request-fields']

[[resources-members-login]]
=== 로그인

[[resources-members-login-successful]]
===== 성공
operation::members/login[snippets='http-request,http-response,request-fields']

[[resources-members-login-fail]]
==== 실패

[[resources-members-login-fail-not-exist-email]]
===== 존재하지 않는 이메일
operation::members/login-with-not-exist-email[snippets='http-request,http-response,request-fields']

[[resources-members-login-fail-not-match-password]]
===== 비밀번호 불일치
operation::members/login-with-wrong-password[snippets='http-request,http-response,request-fields']

[[resources-members-get]]
=== 회원 정보 조회

[[resources-members-get-successful]]
===== 성공
operation::members/get[snippets='http-request,http-response']

[[resources-members-get-fail]]
==== 실패

[[resources-members-get-fail-not-login]]
===== 토큰이 존재하지 않음
operation::members/not-exist-get[snippets='http-request,http-response']


[[resources-members-update]]
=== 회원 정보 수정

[[resources-members-update-successful]]
===== 성공
operation::members/update[snippets='http-request,http-response,request-fields']

[[resources-members-update-fail]]
==== 실패

[[resources-members-update-fail-not-login]]
===== 토큰이 존재하지 않음
operation::members/not-exist-token-update[snippets='http-request,http-response,request-fields,response-fields']

[[resources-members-update-fail-not-match-password]]
===== 비밀번호가 올바르지 않
operation::members/not-match-password-update[snippets='http-request,http-response,request-fields,response-fields']

[[resources-members-delete]]
=== 회원 탈퇴

[[resources-members-delete-successful]]
===== 성공
operation::members/delete[snippets='http-request,http-response']

[[resources-members-delete-fail]]
==== 실패

[[resources-members-delete-not-login]]
===== 토큰이 존재하지 않음
operation::members/delete-not-exist-token[snippets='http-request,http-response,response-fields']

[[resources-favorites]]
== 즐겨찾기

[[resources-favorites-create]]
=== 즐겨찾기 추가

[[resources-favorites-create-successful]]
===== 성공
operation::favorites/create[snippets='http-request,http-response,request-fields']

[[resources-favorites-create-fail]]
==== 실패

[[resources-favorites-create-fail-no-login]]
===== 토큰이 존재하지 않음
operation::favorites/create-no-login[snippets='http-request,http-response,request-fields,response-fields']

===== 즐겨찾기 중복
operation::favorites/create-duplicated[snippets='http-request,http-response,request-fields,response-fields']

[[resources-favorites-delete]]
=== 즐겨찾기 삭제

[[resources-favorites-delete-successful]]
===== 성공
operation::favorites/delete[snippets='http-request,http-response']

[[resources-favorites-delete-fail]]
==== 실패

[[resources-favorites-delete-fail-not-login]]
===== 토큰이 존재하지 않음
operation::favorites/delete-not-login[snippets='http-request,http-response, response-fields']



