TRUNCATE TABLE STATION RESTART IDENTITY;
TRUNCATE TABLE LINE RESTART IDENTITY;
TRUNCATE TABLE LINE_STATION RESTART IDENTITY;
TRUNCATE TABLE MEMBER RESTART IDENTITY;
TRUNCATE TABLE FAVORITE RESTART IDENTITY;