SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE favorite RESTART IDENTITY;
TRUNCATE TABLE member RESTART IDENTITY;
TRUNCATE TABLE line_station RESTART IDENTITY;
TRUNCATE TABLE line RESTART IDENTITY;
TRUNCATE TABLE station RESTART IDENTITY;
SET REFERENTIAL_INTEGRITY TRUE;
