DELETE
FROM FAVORITE;
DELETE
FROM STATION;
DELETE
FROM LINE;
DELETE
FROM LINE_STATION;
DELETE
FROM MEMBER;

ALTER TABLE STATION
    ALTER COLUMN id RESTART WITH 1;
ALTER TABLE LINE
    ALTER COLUMN id RESTART WITH 1;
ALTER TABLE MEMBER
    ALTER COLUMN id RESTART WITH 1;